---
name: 🐛 Bug report
about: Create a report to help us improve
title: '[Bug]: '
labels: bug
issue_body: false  # default: true
inputs:
- type: description
  attributes:
    value: >-
      **Thanks for taking a minute to file a bug report!**
      _Please fill out the form below with as many precise
      details as possible._

- type: textarea
  attributes:
    label: Describe the bug
    description: >-
      A clear and concise description of what the bug is.
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    value: |
      1. Have certain environment
      2. Run given code snippet in a certain way
      3. See some behavior described
    required: true

- type: textarea
  attributes:
    label: Description
    description: >-
      A clear and concise description of what you expected to happen.
    required: true

- type: textarea
  attributes:
    label: Logs/tracebacks
    description: |
      If applicable, add logs/tracebacks to help explain your problem.

      Paste the output of the steps above, including the commands
      themselves and their output/traceback etc.
    value: |
      ```console

      ```
    required: true

- type: input
  attributes:
    label: >-
      Your version of the Python
    description: >-
      Attach your version of the Python.
    required: true
- type: input
  attributes:
    label: Your version of the multidict distribution
    description: >-
      Attach your version of the multidict distribution.
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: >-
      Add any other context about the problem here.

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [aio-libs Code of Conduct][CoC] first.

      [CoC]: https://github.com/aio-libs/.github/blob/master/CODE_OF_CONDUCT.md
    choices:
    - label: I agree to follow the aio-libs Code of Conduct
      required: true
...
