name: 🚀 Feature request
description: Suggest a new feature or change to pydantic
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to pydantic! ✊

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.
        
        _Sorry to sound so draconian 👿; but every second spent replying to issues is time not spent improving pydantic 🙇._
      options:
        - label: I have searched Google & GitHub for similar requests and couldn't find anything
          required: true
        - label: I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏
        
        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Why the feature should be added to pydantic (as opposed to another library or just implemented in your code)
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which of the following parts of pydantic does this feature affect?
      options:
        - label: Data validation/parsing
        - label: Data serialization (e.g. `.dict()`)
        - label: JSON Schema
        - label: Dataclasses
        - label: Field Types (e.g. adding or changing a particular data type)
        - label: Settings Management
        - label: Plugins and integration with other tools (mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.)

