name: cherry-pick

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cherry_pick:
    runs-on: ubuntu-latest

    name: Cherry pick into 1.10.X-fixes

    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'cherry-pick-v1')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into 1.10.X-fixes
        uses: samuelcolvin/github-cherry-pick-action@title-body-sub
        with:
          branch: 1.10.X-fixes
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'
