name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir site
        echo '<h1>this is a simple site</h1>' > site/index.html
        echo foobar > site/another.txt

    - name: Store docs site
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: site

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: "echo 'job:    ${{ toJSON(job) }}'"
    - run: "echo 'github: ${{ toJSON(github) }}'"
    - run: "echo 'env:    ${{ toJSON(env) }}'"

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: pip install coverage

    - run: mkdir coverage

    - run: coverage run demo.py
      env:
        COVERAGE_FILE: coverage/.coverage.linux-testing
        CONTEXT: linux-py3.8-testing

    - run: ls -la coverage

    - name: Store coverage files
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage

  store-coverage:
    name: coverage check
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: get coverage files
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage

      - run: pip install coverage

      - run: ls -la
      - run: coverage combine coverage
      - run: coverage report
      - run: coverage html --show-contexts

      - name: Store coverage html
        uses: actions/upload-artifact@v2
        with:
          name: coverage-html
          path: htmlcov

  deploy:
    name: Test Deploy
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install
        run: pip install -U twine packaging

      - name: check tag
        id: check-tag
        run: ./tests/check_tag.py

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}

      - name: publish docs
        if: '!fromJSON(steps.check-tag.outputs.IS_PRERELEASE)'
        run: echo publishing
