name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          curl https://api.github.com/repos/samuelcolvin/pydantic -H "Authorization: bearer $TOKEN"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
