on: push

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: python -m pip install -U httpie

      - name: http
        run: |
          echo $TOKEN | wc
          http -p hbHB https://api.github.com/user "Authorization:bearer $TOKEN" "Accept:application/vnd.github.v3+json"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
