name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir site
        echo '<h1>this is a simple site</h1>' > site/index.html
        echo foobar > site/another.txt

    - name: Store docs site
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: site

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: pip install coverage

    - run: mkdir coverage

    - run: coverage run ../pydantic-sandbox/demo.py
      env:
        COVERAGE_FILE: coverage/.coverage.linux-testing
        CONTEXT: linux-py3.8-testing

    - run: ls -la coverage

    - name: Store coverage files
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
