on: push

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: python -m pip install -U httpie

      - run: |
          http -p hbHB GET https://api.github.com/user "Authorization:bearer $TOKEN" "Accept:application/vnd.github.v3+json"
          echo $TOKEN | wc
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          curl https://api.github.com/user -H "Authorization:bearer $TOKEN" -H "Accept:application/vnd.github.v3+json"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
