name: Label & Assign

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: samuelcolvin/label-and-assign@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: samuelcolvin
