name: Label & Assign

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: samuelcolvin/label-and-assign@5c4be1f18e6338541354b701bd4c8d18c5bcc120
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: samuelcolvin
