name: Assign Pull Requests

on:
  issue_comment:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:

      - run: cat "$GITHUB_EVENT_PATH"

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: pip install pydantic pygithub

      - run: python assign_reviewers.py
