name: Upload Previews

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  coverage-upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: pip install smokeshow

      - name: get coverage html
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: coverage-html
          path: htmlcov

      - run: smokeshow upload htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage} SNAP
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 100
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}

  docs-upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: pip install smokeshow

      - name: get docs site
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: docs
          path: site

      - run: smokeshow upload site
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Docs Preview
          SMOKESHOW_GITHUB_CONTEXT: docs
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
